name: Build & Deploy Website
on:
  push:
    branches-ignore:
      - 'gh-pages'
  pull_request:
    branches-ignore:
      - 'gh-pages'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install OS packages
        run: sudo apt update && sudo apt install -y libffi-dev
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Install requirements.txt
        run: pip install -r requirements.txt
      - name: Setup git
        run: |
          git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          git fetch origin gh-pages
      - name: Deploy upcoming
        run: mike deploy upcoming --push
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy version
        run: mike deploy "$GITHUB_REF_NAME" --push
        if: startsWith(github.ref, 'refs/heads/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}